### ISSUE TITLE
Generate code from feature doesn't work

### ISSUE THREAD

**Issue by mburakkalkan** [PeterPorzuczek/jest-cucumber-code-generator-extension#25]
Using VS Code 1.7.5
Using .feature extension

It was working good before but since after recent VS code versions (don't know what the exact version), "Generate code from feature" command does nothing now, and no errors throwing.

**Comment by PeterPorzuczek** [comment]
Tested on 1.75.0 and everything is ok, maybe you need privileges on your system to access clipboard. Closing as I can't replicate the issue.
